### ISSUE TITLE
Can't download the King's College Dataset?

### ISSUE THREAD

**Issue by Zeit42** [youngguncho/PoseNet-Pytorch#1]
I tried both the wget command, and going to the link that directed me to the University of Cambridge site, but I got a proxy error for both attempts. 

Is there any way to download the dataset?

**Comment by youngguncho** [comment]
I checked the link, and I think the error of the dataset server is fixed now. 
The direct link to the King's college dataset is below.
https://www.repository.cam.ac.uk/handle/1810/251342
