### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by hgarud** [youngguncho/PoseNet-Pytorch#3]
Hi,
Great work on the repo!
I couldn't find any links/reference to any pretrained model files for a quick test.

Thanks

**Comment by youngguncho** [comment]
I'm sorry for the late response. 
Recently, I deleted pre-trained model, but I can make one easily (only on Kingscollege dataset).
If you want the pre-trained model, I will retrain and share the model.
Thank you.

**Comment by hgarud** [comment]
If it is not too much trouble, that would be great :)

**Comment by youngguncho** [comment]
Thank you for your patience. 
I retrain the model, and you can download the trained model by the following link.
https://www.dropbox.com/s/3x9su2nevo608od/best_net.pth?dl=0
The test.py script will automatically load the 'best_net.pth' in '@src_path/models_Kingcollege/'. 
Also, the model is not fully optimized for the best performance.
